### ISSUE TITLE
Feature: Add basic TLS support

### ISSUE THREAD

**Issue by mwacker-sms** [dmikusa/tiny-health-checker#21]
Since i love the simplicity of this tool and i really appreciate it for running health-checks in docker for example for containerized Spring Boot Applications, i need to support HTTPS calls, since the applications i would like to use it for do not allow any request without TLS.

So i think it would be great to support HTTPS calls. Of course I am aware, that fully supporting TLS might be a task which exeeds the simple approach of this tool. But even without any of the more complicated certificate and chain verification tasks which would of course involve much than a simple tool like this could and should provide, this could be very helpful. Since I do not want to compromise the application security configuration to support plain HTTP requests for local health-check calls.

I am not sure, if this issue is correctly addressed here or should be addressed directly at the buildpack-repo at https://github.com/paketo-buildpacks/health-checker.

**Comment by dmikusa** [comment]
See https://github.com/dmikusa/tiny-health-checker/pull/22#issuecomment-2017176111
